### ISSUE TITLE
fix riv appname and icon

### ISSUE THREAD

**Issue by riverscuomo** [riverscuomo/public-bug-hunt#65]

**Comment by riverscuomo** [comment]
Changing App Title:

1. Navigate to the AndroidManifest.xml file in 'android/app/src/main/'.
2. Now, locate the line that reads "<application android:label="app_name">." Replace 'app_name' with your desired app name.

Next, to change the iOS name, use these steps:

1. Open your project in Xcode, after which you need to select the Runner from the project navigation.
2. You have to replace the 'Bundle Name' with your new app name within the 'Info.plist' file.

Changing App Icon:

Firstly, you need to add the 'flutter_launcher_icons' package to your pubspec.yaml file:

```yaml
dev_dependencies:  
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
```

Replace the 'image_path' with the destination of your logo in your project. Now you should run the package to change the app icon:

```
$ flutter pub get
$ flutter pub run flutter_launcher_icons:main 
```
Hopefully, after executing these steps, you should have your custom app name and icon. Make sure you replace the default names and locations with the correct ones for your particular project.
